// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {tray} from '../models';

export function AddTile(arg1:config.Tile):Promise<void>;

export function ExecuteAction(arg1:string,arg2:string):Promise<void>;

export function ExecuteActionWithPath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAutoStartEnabled():Promise<boolean>;

export function GetConfig():Promise<config.Config>;

export function GetTiles():Promise<Array<config.Tile>>;

export function HidePanel():Promise<void>;

export function IsVisible():Promise<boolean>;

export function OpenFolderDialog():Promise<string>;

export function QuitApp():Promise<void>;

export function RemoveTile(arg1:string):Promise<void>;

export function SaveConfig():Promise<void>;

export function SaveTiles(arg1:Array<config.Tile>):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetTrayManager(arg1:tray.Manager):Promise<void>;

export function ShowPanel():Promise<void>;

export function TogglePanel():Promise<void>;

export function UpdateConfig(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:number):Promise<void>;

export function UpdateTile(arg1:string,arg2:config.Tile):Promise<void>;
