// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTile(arg1) {
  return window['go']['main']['App']['AddTile'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DownloadAndApplyUpdate() {
  return window['go']['main']['App']['DownloadAndApplyUpdate']();
}

export function ExecuteAction(arg1, arg2) {
  return window['go']['main']['App']['ExecuteAction'](arg1, arg2);
}

export function ExecuteActionWithPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteActionWithPath'](arg1, arg2, arg3);
}

export function GetAutoStartEnabled() {
  return window['go']['main']['App']['GetAutoStartEnabled']();
}

export function GetCheckForUpdatesOnStartup() {
  return window['go']['main']['App']['GetCheckForUpdatesOnStartup']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetTiles() {
  return window['go']['main']['App']['GetTiles']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function HidePanel() {
  return window['go']['main']['App']['HidePanel']();
}

export function IsVisible() {
  return window['go']['main']['App']['IsVisible']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RemoveTile(arg1) {
  return window['go']['main']['App']['RemoveTile'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SaveTiles(arg1) {
  return window['go']['main']['App']['SaveTiles'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetTrayManager(arg1) {
  return window['go']['main']['App']['SetTrayManager'](arg1);
}

export function ShowPanel() {
  return window['go']['main']['App']['ShowPanel']();
}

export function ShowPanelWithView(arg1) {
  return window['go']['main']['App']['ShowPanelWithView'](arg1);
}

export function TogglePanel() {
  return window['go']['main']['App']['TogglePanel']();
}

export function UpdateConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTile(arg1, arg2) {
  return window['go']['main']['App']['UpdateTile'](arg1, arg2);
}
